# Generated by Django 4.1.6 on 2023-02-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pack_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='status',
        ),
    ]
